# PyTorch Tensors

- This tutorial briefly describes some basic operations on Tensors in PyTorch. 
- This [documentation](http://pytorch.org/docs/master/torch.html) from pytorch contains information about all the possible operations on Tensors.

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
torch.manual_seed(0)
np.random.seed(0)

## Getting started with Tensors

### Creating a Tensor

In [3]:
#Create Torch Tensor from a list
x = torch.Tensor([[1,2,3],[4,5,6]])
print (x) # prints the tensor
print ('shape: ',x.shape) # returns the shape of the tensor. You can also use x.size()

tensor([[1., 2., 3.],
        [4., 5., 6.]])
shape:  torch.Size([2, 3])


- you can use the `.numpy()` function to obtain the numpy array from tensor.

In [4]:
print ('numpy array: ')
print (x.numpy()) # obtains the numpy array from the pytorch Tensor

numpy array: 
[[1. 2. 3.]
 [4. 5. 6.]]


- The default `torch.Tensor` is a float tensor as you can see above.
- You can use `torch.LongTensor` for tensor of integer types.

In [5]:
x = torch.LongTensor([1,4,6])
print (x) # prints the tensor
print ('shape: ', x.shape) # returns the shape of the tensor. You can also use x.size()
print ('numpy array: ',x.numpy()) #obtains the numpy array

tensor([1, 4, 6])
shape:  torch.Size([3])
numpy array:  [1 4 6]


- You can also create Tensors from numpy arrays

In [6]:
one_arr = np.ones(5) # a numpy array
print (one_arr)

[1. 1. 1. 1. 1.]


In [7]:
x = torch.from_numpy(one_arr)
print (x) 
print (x.shape) #obtains the shape of the tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.Size([5])


In [8]:
print (x.numpy()) #obtains the numpy array from the Tensor

[1. 1. 1. 1. 1.]


### Indexing into a Tensor

In [9]:
a = np.random.rand(3,4,5)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[[0.5488, 0.7152, 0.6028, 0.5449, 0.4237],
         [0.6459, 0.4376, 0.8918, 0.9637, 0.3834],
         [0.7917, 0.5289, 0.5680, 0.9256, 0.0710],
         [0.0871, 0.0202, 0.8326, 0.7782, 0.8700]],

        [[0.9786, 0.7992, 0.4615, 0.7805, 0.1183],
         [0.6399, 0.1434, 0.9447, 0.5218, 0.4147],
         [0.2646, 0.7742, 0.4562, 0.5684, 0.0188],
         [0.6176, 0.6121, 0.6169, 0.9437, 0.6818]],

        [[0.3595, 0.4370, 0.6976, 0.0602, 0.6668],
         [0.6706, 0.2104, 0.1289, 0.3154, 0.3637],
         [0.5702, 0.4386, 0.9884, 0.1020, 0.2089],
         [0.1613, 0.6531, 0.2533, 0.4663, 0.2444]]], dtype=torch.float64)
shape:  torch.Size([3, 4, 5])


In [10]:
# you can index into them like arrays
print (x[0]) #gives you a matrix Tensor
print (x[0].shape)

tensor([[0.5488, 0.7152, 0.6028, 0.5449, 0.4237],
        [0.6459, 0.4376, 0.8918, 0.9637, 0.3834],
        [0.7917, 0.5289, 0.5680, 0.9256, 0.0710],
        [0.0871, 0.0202, 0.8326, 0.7782, 0.8700]], dtype=torch.float64)
torch.Size([4, 5])


In [11]:
# you can index into them like arrays
print (x[0][2]) # gives you a vector Tensor
print (x[0][2].shape)

tensor([0.7917, 0.5289, 0.5680, 0.9256, 0.0710], dtype=torch.float64)
torch.Size([5])


In [12]:
print (x[0][2][3]) #this gives you a scalar

tensor(0.9256, dtype=torch.float64)


### Reshaping a Tensor

- To reshape a tensor to a different size, you can use the `.view()` function. 
- The `.view()` function returns a tensor with the same data as the self tensor but of a different size

In [13]:
a = np.random.rand(2,6)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[0.1590, 0.1104, 0.6563, 0.1382, 0.1966, 0.3687],
        [0.8210, 0.0971, 0.8379, 0.0961, 0.9765, 0.4687]], dtype=torch.float64)
shape:  torch.Size([2, 6])


In [14]:
y = x.view(3,4) #reshapes it into a tensor of size 3 x 4
print (y)
print (y.shape)

tensor([[0.1590, 0.1104, 0.6563, 0.1382],
        [0.1966, 0.3687, 0.8210, 0.0971],
        [0.8379, 0.0961, 0.9765, 0.4687]], dtype=torch.float64)
torch.Size([3, 4])


In [15]:
y = x.view(2,3,2) #reshapes the tensor into 2 x 3 x 2
print (y)
print (y.shape)

tensor([[[0.1590, 0.1104],
         [0.6563, 0.1382],
         [0.1966, 0.3687]],

        [[0.8210, 0.0971],
         [0.8379, 0.0961],
         [0.9765, 0.4687]]], dtype=torch.float64)
torch.Size([2, 3, 2])


- if one of the dimensions is `-1`, as shown below, then its size can be inferred. So, you cannot have multiple -1's in view.

In [16]:
y = x.view(4,3) #reshapes the tensor into 4x3
print (y)
print (y.shape)

tensor([[0.1590, 0.1104, 0.6563],
        [0.1382, 0.1966, 0.3687],
        [0.8210, 0.0971, 0.8379],
        [0.0961, 0.9765, 0.4687]], dtype=torch.float64)
torch.Size([4, 3])


In [17]:
y = x.view(4,-1) #same as above, but the second dimension can be inferred.
print (y)
print (y.shape)

tensor([[0.1590, 0.1104, 0.6563],
        [0.1382, 0.1966, 0.3687],
        [0.8210, 0.0971, 0.8379],
        [0.0961, 0.9765, 0.4687]], dtype=torch.float64)
torch.Size([4, 3])


### Operations on Tensors

- You can do some basic operations on tensors like arrays

In [18]:
a = np.random.rand(1,5)
x = torch.from_numpy(a)
print (x)
print (x.shape)

tensor([[0.9768, 0.6048, 0.7393, 0.0392, 0.2828]], dtype=torch.float64)
torch.Size([1, 5])


In [19]:
b = np.ones((1,5))
y = torch.from_numpy(b)
print (y)
print (y.shape)

tensor([[1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([1, 5])


In [20]:
print (x + y) #element wise addition

tensor([[1.9768, 1.6048, 1.7393, 1.0392, 1.2828]], dtype=torch.float64)


In [21]:
print (x - y) #element wise subtraction

tensor([[-0.0232, -0.3952, -0.2607, -0.9608, -0.7172]], dtype=torch.float64)


In [22]:
print (x * y)  #element wise multiplication

tensor([[0.9768, 0.6048, 0.7393, 0.0392, 0.2828]], dtype=torch.float64)


- Another useful operation on tensors is concatenation.
- You can use the `torch.cat()` function, it takes in a list/sequence of tensors and concatenates them

In [23]:
torch.cat([x,y]) # concatenates them along the row (dim=0) by default.

tensor([[0.9768, 0.6048, 0.7393, 0.0392, 0.2828],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], dtype=torch.float64)

In [24]:
torch.cat([x,y], dim=1) # concatenates them along the column when dim=1 is mentioned.

tensor([[0.9768, 0.6048, 0.7393, 0.0392, 0.2828, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]], dtype=torch.float64)

- If you want to expand a Tensor along the singleton dimension, you can use the `.expand()` function.

In [25]:
x = torch.Tensor([[1],[2],[3]])
print (x)
print (x.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [26]:
x.expand(3,4) #expands it along the second dimension from (3 x 1) to be (3 x 4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [27]:
x = torch.Tensor([5,6]).view(-1,2) #reshaping it to 1 x 2
x.expand(5,2) #expands it along the first dimension from (1 x 2) to (5 x 2)

tensor([[5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.]])

- These are the basic operations on the Tensors that might be useful. You can check the [documentation here](http://pytorch.org/docs/master/torch.html) for all list of operations.